# Generated by Django 4.1 on 2023-12-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collectsessionmodel_groupmodel_usermodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectentrymodel',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='collectentrymodel',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='leader_user_id',
        ),
        migrations.RemoveField(
            model_name='membermodel',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='moderatormodel',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='moderatormodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='BalanceEntryModel',
        ),
        migrations.DeleteModel(
            name='CollectEntryModel',
        ),
        migrations.DeleteModel(
            name='CollectSessionModel',
        ),
        migrations.DeleteModel(
            name='GroupModel',
        ),
        migrations.DeleteModel(
            name='MemberModel',
        ),
        migrations.DeleteModel(
            name='ModeratorModel',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
