# Generated by Django 4.1 on 2023-12-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("balance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balanceentry",
            name="date",
        ),
        migrations.RemoveField(
            model_name="balanceentry",
            name="session_id",
        ),
        migrations.AddField(
            model_name="balanceentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2023-12-24 00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="balanceentry",
            name="name",
            field=models.CharField(default="A balance entry", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="balanceentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="balanceentry",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
