# Generated by Django 4.1 on 2023-12-23 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_remove_balanceentry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceentry',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
