# Generated by Django 4.1 on 2024-01-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('collect_session', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectsession',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_sessions', to='group.group'),
        ),
        migrations.AddField(
            model_name='collectentry',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_entries', to='member.member'),
        ),
        migrations.AddField(
            model_name='collectentry',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_entries', to='collect_session.collectsession'),
        ),
        migrations.AlterUniqueTogether(
            name='collectentry',
            unique_together={('session_id', 'member_id')},
        ),
    ]
