# Generated by Django 4.1 on 2023-12-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect_session', '0002_collectentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectsession',
            name='description',
        ),
    ]
