# Generated by Django 4.1 on 2023-12-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('collect_session', '0003_remove_collectsession_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectsession',
            name='amount_per_member',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='collectentry',
            unique_together={('session_id', 'member_id')},
        ),
        migrations.RemoveField(
            model_name='collectentry',
            name='amount',
        ),
    ]
