# Generated by Django 4.1 on 2023-12-23 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_remove_balanceentry_date_and_more'),
        ('group', '0004_group_updated_at'),
        ('collect_session', '0004_collectsession_amount_per_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectsession',
            old_name='amount_per_member',
            new_name='payment_per_member',
        ),
        migrations.AddField(
            model_name='collectsession',
            name='balance_entry_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_entry', to='balance.balanceentry'),
        ),
        migrations.AddField(
            model_name='collectsession',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collect_sessions', to='group.group'),
            preserve_default=False,
        ),
    ]
