# Generated by Django 4.1 on 2023-12-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_session', '0005_rename_amount_per_member_collectsession_payment_per_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectsession',
            name='description',
            field=models.CharField(default='description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectsession',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
