# Generated by Django 4.1 on 2023-12-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_session', '0006_collectsession_description_collectsession_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-12-24 02:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collectsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-12-24 02:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
