# Generated by Django 4.1 on 2023-12-16 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Moderator",
        ),
    ]
