# Generated by Django 4.1 on 2023-12-16 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0002_delete_moderator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectentry",
            name="member_id",
        ),
        migrations.RemoveField(
            model_name="collectentry",
            name="session_id",
        ),
        migrations.RemoveField(
            model_name="member",
            name="group_id",
        ),
        migrations.DeleteModel(
            name="BalanceEntry",
        ),
        migrations.DeleteModel(
            name="CollectEntry",
        ),
        migrations.DeleteModel(
            name="CollectSession",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
