# Generated by Django 4.1 on 2023-12-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
